// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACqIoQVD3d-L4VS-aNzNyofwt0H3XsRwk',
    appId: '1:643639209344:web:1c0e46e50624097500e565',
    messagingSenderId: '643639209344',
    projectId: 'techsolver-2ef90',
    authDomain: 'techsolver-2ef90.firebaseapp.com',
    storageBucket: 'techsolver-2ef90.appspot.com',
    measurementId: 'G-P9NKLV1X1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB9d4O-3QrTxxV33R7nfuLzWDOUkcW60g',
    appId: '1:643639209344:android:11e8ed4f308d47dd00e565',
    messagingSenderId: '643639209344',
    projectId: 'techsolver-2ef90',
    storageBucket: 'techsolver-2ef90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQC17hUVdGWqAzX1PI59BfCgx5pPych4I',
    appId: '1:643639209344:ios:cadf143b856d14ba00e565',
    messagingSenderId: '643639209344',
    projectId: 'techsolver-2ef90',
    storageBucket: 'techsolver-2ef90.appspot.com',
    iosBundleId: 'com.example.flutterApp12e4.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQC17hUVdGWqAzX1PI59BfCgx5pPych4I',
    appId: '1:643639209344:ios:cadf143b856d14ba00e565',
    messagingSenderId: '643639209344',
    projectId: 'techsolver-2ef90',
    storageBucket: 'techsolver-2ef90.appspot.com',
    iosBundleId: 'com.example.flutterApp12e4.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACqIoQVD3d-L4VS-aNzNyofwt0H3XsRwk',
    appId: '1:643639209344:web:e7967ba4d306efb800e565',
    messagingSenderId: '643639209344',
    projectId: 'techsolver-2ef90',
    authDomain: 'techsolver-2ef90.firebaseapp.com',
    storageBucket: 'techsolver-2ef90.appspot.com',
    measurementId: 'G-95QCM75JJS',
  );
}
